const SCENARIOS={current:{name:'Current',spread_km:2,crosswind_km:1},adverse:{name:'Adverse',spread_km:5,crosswind_km:2},severe:{name:'Severe',spread_km:10,crosswind_km:4}};
const state={event:null,risk:null,exposure:null,scenario:'current',timeline:[],at:3,actions:[],sources:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const helpLink=document.createElement('a');helpLink.href='help.html';helpLink.className='help-link';helpLink.textContent='Help / demo guide';document.querySelector('.topbar')?.insertBefore(helpLink,document.querySelector('.reset-btn'));
const showcaseTitle=document.querySelector('.emerging .panel-title b');if(showcaseTitle)showcaseTitle.textContent='Showcase event';const showcaseCount=document.querySelector('.emerging .count-badge');if(showcaseCount)showcaseCount.textContent='1 deterministic event';
const radarMapSubtitle=document.querySelector('#screen-radar .map-panel .subtle');if(radarMapSubtitle)radarMapSubtitle.textContent='Regional event prioritisation · all active signals';const intelligenceMapSubtitle=document.querySelector('#screen-intelligence .map-panel .subtle');if(intelligenceMapSubtitle)intelligenceMapSubtitle.textContent='Local signal detail · detections, warning and wind';
const fmt=n=>new Intl.NumberFormat('de-DE').format(Math.round(n||0));
const euro=n=>{n=Math.round(n||0); if(Math.abs(n)>=1e9)return `€${(n/1e9).toFixed(1).replace('.',',')}bn`; if(Math.abs(n)>=1e6)return `€${(n/1e6).toFixed(1).replace('.',',')}m`; return `€${fmt(n)}`};
const title=s=>s.charAt(0).toUpperCase()+s.slice(1);
async function api(path){const r=await fetch(path); if(!r.ok)throw Error(await r.text()); return r.json()}
function metric(label,value,sub,accent=''){return `<div class="metric-card ${accent}"><span>${label}</span><strong>${value}</strong><small>${sub||''}</small></div>`}
const leafletMaps={},leafletLayers={};
const MAP_VIEWS={radar:{id:'radar-map',center:[50.92,6.58],zoom:9},intelligence:{id:'intel-map',center:[50.69,6.37],zoom:11},portfolio:{id:'portfolio-map',center:[51.05,6.82],zoom:8},scenario:{id:'scenario-map',center:[50.69,6.37],zoom:11}};
const PORTFOLIO_CENTRES=[['Cologne',50.9375,6.9603,3200],['Düsseldorf',51.2277,6.7735,2500],['Aachen',50.7753,6.0839,1800],['Bonn',50.7374,7.0982,1800],['Düren',50.8043,6.482,1800],['Essen',51.4556,7.0116,1800],['Dortmund',51.5136,7.4653,1600],['Wuppertal',51.2562,7.1508,1500],['Hürtgenwald',50.69,6.37,6000]];
function setupLeafletMaps(){if(!window.L)return;Object.values(MAP_VIEWS).forEach(view=>{const host=$(`#${view.id}`);if(!host||leafletMaps[view.id])return;const map=L.map(host,{zoomControl:false,preferCanvas:true}).setView(view.center,view.zoom);map.attributionControl.setPrefix(false);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);leafletMaps[view.id]=map;leafletLayers[view.id]=L.layerGroup().addTo(map)})}
function addScenario(layer){const feature=state.exposure?.scenario_geometry;if(feature)L.geoJSON(feature,{style:{color:'#f59e62',weight:3,dashArray:'8 6',fillColor:'#f59e62',fillOpacity:.18}}).addTo(layer)}
function addEvent(layer,label=true){L.circle([state.event.centroid.latitude,state.event.centroid.longitude],{radius:state.event.event_radius_km*1000,color:'#f2645d',weight:2,fillColor:'#f2645d',fillOpacity:.12}).addTo(layer);L.circleMarker([state.event.centroid.latitude,state.event.centroid.longitude],{radius:7,color:'#ffe2d2',weight:2,fillColor:'#f2645d',fillOpacity:.95}).bindTooltip(label?state.event.name:'Observed fire area').addTo(layer)}
function addFirms(layer){state.firms.forEach((f,i)=>L.circleMarker([f.latitude,f.longitude],{radius:5+i*.4,color:'#fff0c7',weight:1,fillColor:'#f2645d',fillOpacity:.9}).bindTooltip(`NASA FIRMS · ${f.satellite}<br>FRP ${f.frp} MW`).addTo(layer))}
function updateLeafletLayers(){if(!window.L||!state.event||!state.firms)return;Object.entries(leafletLayers).forEach(([id,layer])=>{layer.clearLayers();if(id==='radar-map'){addScenario(layer);if(state.warning?.geometry)L.geoJSON(state.warning.geometry,{style:{color:'#f6c85f',weight:2,dashArray:'3 5',fillColor:'#f6c85f',fillOpacity:.08}}).addTo(layer);addEvent(layer);addFirms(layer)}else if(id==='intel-map'){if(state.warning?.geometry)L.geoJSON(state.warning.geometry,{style:{color:'#f6c85f',weight:2,dashArray:'3 5',fillColor:'#f6c85f',fillOpacity:.10}}).addTo(layer);addEvent(layer);addFirms(layer);const windEnd=[state.event.centroid.latitude+.025,state.event.centroid.longitude+.055];L.polyline([[state.event.centroid.latitude,state.event.centroid.longitude],windEnd],{color:'#55d4dc',weight:3}).bindTooltip(`Wind ${state.event.wind_direction}° · ${state.event.wind_speed_kmh} km/h`).addTo(layer)}else if(id==='portfolio-map'){addScenario(layer);PORTFOLIO_CENTRES.forEach(([name,lat,lon,count])=>L.circleMarker([lat,lon],{radius:Math.max(8,Math.sqrt(count)/3),color:'#55d4dc',weight:1,fillColor:'#55d4dc',fillOpacity:.28}).bindTooltip(`${name}<br>${fmt(count)} synthetic policies`).addTo(layer));addEvent(layer)}else if(id==='scenario-map'){addScenario(layer);addEvent(layer,false)}})}
function setMapView(name){const view=MAP_VIEWS[name],map=view&&leafletMaps[view.id];if(!map)return;map.invalidateSize({pan:false});if(name==='scenario'&&state.exposure?.scenario_geometry){const bounds=L.geoJSON(state.exposure.scenario_geometry).getBounds();map.fitBounds(bounds.pad(.55),{animate:false,maxZoom:12})}else map.setView(view.center,view.zoom,{animate:false})}
function renderSources(){const box=$('#source-list');box.innerHTML=Object.entries(state.sources||{}).map(([name,v])=>`<div class="source-row"><span class="source-led ${v.status==='fallback'?'amber':''}"></span><span>${name.replace(' / Copernicus','')}</span><small>${v.status==='fallback'?'Fallback':v.freshness_minutes+'m old'}</small></div>`).join('');$('#mode-label').textContent=(state.mode||'demo').toUpperCase()+' MODE';}
function renderTimeline(){const box=$('#timeline-points');if(!box)return;$('#timeline-label').textContent=state.timeline[state.at]?.label||'Final snapshot';box.innerHTML=state.timeline.map((snap,i)=>`<button class="timeline-point ${i===state.at?'active':''}" data-at="${i}"><i></i><span>${snap.label}</span><b>Risk ${snap.risk_score}</b></button>`).join('');$$('.timeline-point').forEach(b=>b.onclick=async()=>{state.at=Number(b.dataset.at);await refresh();renderTimeline();toast(`Replay: ${state.timeline[state.at].label}`)})}
function renderRadar(){const exposure=state.exposure;$('#radar-metrics').innerHTML=metric('ACTIVE EVENTS','01','Historical showcase')+metric('HIGH-RISK EVENTS','01','Risk score ≥ 75','orange')+metric('POLICIES NEAR EVENT',fmt(exposure.bands['5_10km'].policies),'Within 10 km')+metric('TIV POTENTIALLY EXPOSED',euro(exposure.bands['5_10km'].tiv),'5–10 km view','red');$('#event-list').innerHTML=`<button class="event-row" data-screen="intelligence"><span class="event-rank">01</span><span><b>Hürtgenwald Wildfire</b><small>Hürtgenwald · Kreis Düren</small></span><strong>${state.risk.score}<small> / 100</small></strong><em>↑</em></button>`;$$('.event-row').forEach(b=>b.onclick=()=>showScreen('intelligence'))}
function renderRisk(){const r=state.risk;$('#risk-score').textContent=r.score;$('#confidence').textContent=`${r.confidence_percent}%`;$('#confidence-bar').style.width=`${r.confidence_percent}%`;$('#trend').textContent=title(r.trend);$('#component-list').innerHTML=Object.entries(r.components).map(([k,v])=>`<div class="component"><span>${k.replace('_',' ')}</span><b>${Math.round(v)}</b><i><em style="width:${v}%"></em></i></div>`).join('');$('#provenance').innerHTML=Object.entries(state.sources).map(([k,v])=>`<div class="provenance-row"><b>${k}</b><span class="source-led ${v.status==='fallback'?'amber':''}"></span><small>${v.status==='fallback'?'fixture fallback':v.freshness_minutes+'m ago'}</small></div>`).join('');}
function renderPortfolio(){const e=state.exposure;$('#portfolio-metrics').innerHTML=metric('POLICIES WITHIN 10 KM',fmt(e.bands['5_10km'].policies),'Distance from event')+metric('TOTAL INSURED VALUE',euro(e.bands['5_10km'].tiv),'Distance-band total','orange')+metric('CURRENT THREAT ENVELOPE',fmt(e.scenario.policies),'Policies intersecting','red')+metric('INDICATIVE INSURED LOSS',`${euro(e.estimates.loss_low)}–${euro(e.estimates.loss_high)}`,'Planning range','red');const rows=[['Event area','inside'],['< 1 km','0_1km'],['1–3 km','1_3km'],['3–5 km','3_5km'],['5–10 km','5_10km']];$('#exposure-table').innerHTML=rows.map(([label,key])=>`<div class="exposure-row"><span>${label}</span><b>${fmt(e.bands[key].policies)}</b><strong>${euro(e.bands[key].tiv)}</strong></div>`).join('')+`<div class="exposure-total"><span>SCENARIO TOTAL</span><b>${fmt(e.scenario.policies)}</b><strong>${euro(e.scenario.tiv)}</strong></div>`}
function renderScenario(){const e=state.exposure,s=SCENARIOS[state.scenario];$('#scenario-name').textContent=title(state.scenario);$('#scenario-geometry-label').textContent=`${title(state.scenario)} · ${s.spread_km} km spread · wind ${String(state.event.wind_direction).padStart(3,'0')}°`;$('#wind-readout').textContent=`${String(state.event.wind_direction).padStart(3,'0')}° / ${state.event.wind_speed_kmh} km/h`;$('#scenario-stats').innerHTML=metric('POLICIES EXPOSED',fmt(e.scenario.policies),'Intersecting envelope')+metric('TOTAL TIV',euro(e.scenario.tiv),'Building + contents','orange')+metric('LOSS RANGE',`${euro(e.estimates.loss_low)}–${euro(e.estimates.loss_high)}`,'Indicative insured loss','red')+metric('EXPECTED CLAIMS',`${fmt(e.estimates.claims_low)}–${fmt(e.estimates.claims_high)}`,'Planning estimate');const r=e.reinsurance;$('#retention').textContent=euro(r.retention);$('#reins-status').innerHTML=`<b>${r.status}</b><span>${r.ceded_loss_high?`Potential ceded loss ${euro(r.ceded_loss_low)}–${euro(r.ceded_loss_high)}`:'No expected treaty recovery'}</span>`;$('#reins-fill').style.width=`${Math.min(100,e.estimates.loss_high/r.retention*100)}%`;$$('#scenario-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.scenario===state.scenario));}
function renderActions(){const severe=state.cache?.severe||state.exposure;$('#action-loss').textContent=`${euro(severe.estimates.loss_low)}–${euro(severe.estimates.loss_high)}`;$('#actions-grid').innerHTML=state.actions.map(a=>`<article class="action-card ${a.status==='Completed'?'done':''}"><div class="action-card-head"><span class="action-team">${a.team}</span><select data-action="${a.id}"><option ${a.status==='Not started'?'selected':''}>Not started</option><option ${a.status==='In progress'?'selected':''}>In progress</option><option ${a.status==='Completed'?'selected':''}>Completed</option></select></div><h3>${a.title}</h3><p>${a.detail}</p><div class="action-foot"><span class="action-check">${a.status==='Completed'?'✓':'○'}</span><span>${a.status}</span></div></article>`).join('');const done=state.actions.filter(a=>a.status==='Completed').length;$('#action-summary').textContent=`${done} / ${state.actions.length} complete`;$$('select[data-action]').forEach(s=>s.onchange=async()=>{const data=await fetch(`/api/actions/${s.dataset.action}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})}).then(r=>r.json());state.actions=data.actions;renderActions();toast('Action status updated')})}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));window.scrollTo(0,0);setTimeout(()=>{setMapView(name);updateLeafletLayers()},120)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function load(){try{const [events,health,timeline,actions]=await Promise.all([api('/api/events'),api('/api/health'),api('/api/events/evt-huertgenwald-2022/timeline'),api('/api/events/evt-huertgenwald-2022/actions')]);state.event=events.events[0];state.sources=health.sources;state.mode=health.mode;state.timeline=timeline.snapshots;state.actions=actions.actions;state.firms=(await api('/api/events/evt-huertgenwald-2022/signals')).firms.observations;state.warning=(await api('/api/events/evt-huertgenwald-2022/signals')).warning.geometry? (await api('/api/events/evt-huertgenwald-2022/signals')).warning:null;state.event.wind_direction=state.event.wind_direction||70;state.event.wind_speed_kmh=state.event.wind_speed_kmh||31;await refresh();renderSources();renderActions();}catch(err){toast('Could not load radar data');console.error(err)}}
async function refresh(){const [risk,exposure]=await Promise.all([api(`/api/events/${state.event.id}/risk?at=${state.at}`),api(`/api/events/${state.event.id}/exposure?scenario=${state.scenario}&at=${state.at}`)]);state.risk=risk;state.exposure=exposure;state.cache=state.cache||{};for(const key of ['current','adverse','severe'])state.cache[key]=await api(`/api/events/${state.event.id}/exposure?scenario=${key}&at=${state.at}`);renderRadar();renderRisk();renderPortfolio();renderScenario();renderActions();$('#updated-label').textContent=state.timeline[state.at]?.label||'Now';}
$$('.nav-item').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$$('.scenario-tabs button').forEach(b=>b.onclick=async()=>{state.scenario=b.dataset.scenario;await refresh();setTimeout(()=>setMapView('scenario'),50)});$$('.toggle-btn').forEach(b=>b.onclick=()=>{if(b.dataset.mode==='live')toast('Live connectors are configured server-side; replay remains the safe demo path');else toast('Historical replay selected')});['#why-risk','#why-risk-2'].forEach(s=>$(s).onclick=()=>$('#why-box').classList.toggle('hidden'));$('#why-exposure').onclick=()=>toast('Counts use point-in-envelope and haversine distance bands; TIV is summed from synthetic policies.');$('#reset-demo').onclick=()=>{state.at=3;state.scenario='current';load();toast('Demo reset to final replay snapshot')};load();
const timelineTimer=setInterval(()=>{if(state.timeline.length){renderTimeline();clearInterval(timelineTimer)}},100);
setupLeafletMaps();
setInterval(()=>{if(state.exposure)updateLeafletLayers()},1000);
setInterval(()=>{if(state.risk){const p=$('#why-box p');if(p)p.textContent=state.risk.method}},500);
