const SCENARIOS={current:{name:'Current',spread_km:2,crosswind_km:1},adverse:{name:'Adverse',spread_km:5,crosswind_km:2},severe:{name:'Severe',spread_km:10,crosswind_km:4}};
const state={event:null,risk:null,exposure:null,scenario:'current',timeline:[],at:3,actions:[],sources:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const helpLink=document.createElement('a');helpLink.href='help.html';helpLink.className='help-link';helpLink.textContent='Help / demo guide';document.querySelector('.topbar')?.insertBefore(helpLink,document.querySelector('.reset-btn'));
const showcaseTitle=document.querySelector('.emerging .panel-title b');if(showcaseTitle)showcaseTitle.textContent='Showcase event';const showcaseCount=document.querySelector('.emerging .count-badge');if(showcaseCount)showcaseCount.textContent='1 deterministic event';
const fmt=n=>new Intl.NumberFormat('de-DE').format(Math.round(n||0));
const euro=n=>{n=Math.round(n||0); if(Math.abs(n)>=1e9)return `€${(n/1e9).toFixed(1).replace('.',',')}bn`; if(Math.abs(n)>=1e6)return `€${(n/1e6).toFixed(1).replace('.',',')}m`; return `€${fmt(n)}`};
const title=s=>s.charAt(0).toUpperCase()+s.slice(1);
async function api(path){const r=await fetch(path); if(!r.ok)throw Error(await r.text()); return r.json()}
function metric(label,value,sub,accent=''){return `<div class="metric-card ${accent}"><span>${label}</span><strong>${value}</strong><small>${sub||''}</small></div>`}
function project(lat,lon,w=900,h=540){const x=(lon-5.45)/(9.05-5.45)*w;const y=h-(lat-50.25)/(52.55-50.25)*h;return [x,y]}
function pathFor(coords){return coords.map((p,i)=>{const [x,y]=project(p[1],p[0]);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')+' Z'}
function baseMap(svg,opts={}){if(!svg)return;const boundary=[[50.34,5.87],[50.45,6.04],[50.45,6.55],[50.50,7.05],[50.62,7.18],[50.8,7.4],[51.0,7.55],[51.28,7.6],[51.55,7.5],[52.1,7.1],[52.35,6.7],[52.4,6.15],[52.25,5.75],[51.9,5.65],[51.55,5.65],[51.2,5.7],[50.85,5.75],[50.55,5.8]];let out=`<rect width="900" height="540" fill="transparent"/><path d="${pathFor(boundary)}" fill="#14253544" stroke="#3a5268" stroke-width="2"/>`;for(let i=0;i<7;i++){let y=80+i*65;out+=`<path d="M30 ${y} H870" class="map-grid"/>`}for(let i=0;i<5;i++){let x=120+i*170;out+=`<path d="M${x} 20 V520" class="map-grid"/>`}out+=`<text x="52" y="48" class="map-label">NORTH RHINE-WESTPHALIA</text><text x="700" y="500" class="map-label muted">50 km</text>`;svg.innerHTML=out}
const leafletMaps={},leafletLayers={};
function setupLeafletMaps(){if(!window.L)return;['radar-map','intel-map','portfolio-map','scenario-map'].forEach(id=>{const svg=$(`#${id}`);if(!svg||leafletMaps[id])return;const wrap=svg.parentElement,el=document.createElement('div');el.className='leaflet-map';wrap.insertBefore(el,svg);const map=L.map(el,{zoomControl:false,preferCanvas:true}).setView([50.69,6.37],8);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);leafletMaps[id]=map;leafletLayers[id]=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),0)})}
function updateLeafletLayers(){if(!window.L||!state.event||!state.firms)return;Object.entries(leafletMaps).forEach(([id,map])=>{const layer=leafletLayers[id];layer.clearLayers();const feature=state.exposure?.scenario_geometry;if(feature)L.geoJSON(feature,{style:{color:'#f59e62',weight:2,dashArray:'7 6',fillColor:'#f59e62',fillOpacity:.14}}).addTo(layer);if(state.warning?.geometry)L.geoJSON(state.warning.geometry,{style:{color:'#f6c85f',weight:2,dashArray:'3 5',fillColor:'#f6c85f',fillOpacity:.08}}).addTo(layer);state.firms.forEach((f,i)=>L.circleMarker([f.latitude,f.longitude],{radius:5+i*.4,color:'#fff0c7',weight:1,fillColor:'#f2645d',fillOpacity:.9}).bindTooltip(`NASA FIRMS · ${f.satellite}<br>FRP ${f.frp} MW`).addTo(layer));L.circleMarker([state.event.centroid.latitude,state.event.centroid.longitude],{radius:9,color:'#ffe2d2',weight:2,fillColor:'#f2645d',fillOpacity:.95}).bindTooltip(state.event.name).addTo(layer)})}
function drawEvent(svg,scenarioFeature=null,portfolio=false){if(!svg)return;baseMap(svg);const [x,y]=project(state.event.centroid.latitude,state.event.centroid.longitude);let out=svg.innerHTML; if(portfolio){const cells=[['Cologne',50.9375,6.9603,62],['Düsseldorf',51.2277,6.7735,52],['Aachen',50.7753,6.0839,38],['Bonn',50.7374,7.0982,35],['Düren',50.8043,6.482,48],['Essen',51.4556,7.0116,42],['Dortmund',51.5136,7.4653,40],['Wuppertal',51.2562,7.1508,34],['Hürtgenwald',50.69,6.37,88]];cells.forEach(c=>{let [cx,cy]=project(c[1],c[2]);out+=`<circle cx="${cx}" cy="${cy}" r="${c[3]/2}" class="concentration"/><text x="${cx+8}" y="${cy+4}" class="city-label">${c[0]}</text>`})} if(scenarioFeature)out+=`<path d="${pathFor(scenarioFeature.geometry.coordinates[0])}" class="scenario-area"/>`;out+=`<circle cx="${x}" cy="${y}" r="29" class="event-halo"/><circle cx="${x}" cy="${y}" r="8" class="event-core"/><text x="${x+16}" y="${y-15}" class="event-label">HÜRTGENWALD</text>`;state.firms.forEach((f,i)=>{const [fx,fy]=project(f.latitude,f.longitude);out+=`<circle cx="${fx}" cy="${fy}" r="${4+i/2}" class="fire-point"/><circle cx="${fx}" cy="${fy}" r="${9+i}" class="fire-ring"/>`});if(state.warning?.geometry){out+=`<path d="${pathFor(state.warning.geometry.coordinates[0])}" class="warning-area"/>`}svg.innerHTML=out}
function renderSources(){const box=$('#source-list');box.innerHTML=Object.entries(state.sources||{}).map(([name,v])=>`<div class="source-row"><span class="source-led ${v.status==='fallback'?'amber':''}"></span><span>${name.replace(' / Copernicus','')}</span><small>${v.status==='fallback'?'Fallback':v.freshness_minutes+'m old'}</small></div>`).join('');$('#mode-label').textContent=(state.mode||'demo').toUpperCase()+' MODE';}
function renderTimeline(){const box=$('#timeline-points');if(!box)return;$('#timeline-label').textContent=state.timeline[state.at]?.label||'Final snapshot';box.innerHTML=state.timeline.map((snap,i)=>`<button class="timeline-point ${i===state.at?'active':''}" data-at="${i}"><i></i><span>${snap.label}</span><b>Risk ${snap.risk_score}</b></button>`).join('');$$('.timeline-point').forEach(b=>b.onclick=async()=>{state.at=Number(b.dataset.at);await refresh();renderTimeline();toast(`Replay: ${state.timeline[state.at].label}`)})}
function renderRadar(){const exposure=state.exposure;$('#radar-metrics').innerHTML=metric('ACTIVE EVENTS','01','Historical showcase')+metric('HIGH-RISK EVENTS','01','Risk score ≥ 75','orange')+metric('POLICIES NEAR EVENT',fmt(exposure.bands['5_10km'].policies),'Within 10 km')+metric('TIV POTENTIALLY EXPOSED',euro(exposure.bands['5_10km'].tiv),'5–10 km view','red');drawEvent($('#radar-map'),state.exposure.scenario_geometry);$('#event-list').innerHTML=`<button class="event-row" data-screen="intelligence"><span class="event-rank">01</span><span><b>Hürtgenwald Wildfire</b><small>Hürtgenwald · Kreis Düren</small></span><strong>${state.risk.score}<small> / 100</small></strong><em>↑</em></button>`;$$('.event-row').forEach(b=>b.onclick=()=>showScreen('intelligence'))}
function renderRisk(){const r=state.risk;$('#risk-score').textContent=r.score;$('#confidence').textContent=`${r.confidence_percent}%`;$('#confidence-bar').style.width=`${r.confidence_percent}%`;$('#trend').textContent=title(r.trend);$('#component-list').innerHTML=Object.entries(r.components).map(([k,v])=>`<div class="component"><span>${k.replace('_',' ')}</span><b>${Math.round(v)}</b><i><em style="width:${v}%"></em></i></div>`).join('');$('#provenance').innerHTML=Object.entries(state.sources).map(([k,v])=>`<div class="provenance-row"><b>${k}</b><span class="source-led ${v.status==='fallback'?'amber':''}"></span><small>${v.status==='fallback'?'fixture fallback':v.freshness_minutes+'m ago'}</small></div>`).join('');drawEvent($('#intel-map'));}
function renderPortfolio(){const e=state.exposure;$('#portfolio-metrics').innerHTML=metric('POLICIES WITHIN 10 KM',fmt(e.bands['5_10km'].policies),'Distance from event')+metric('TOTAL INSURED VALUE',euro(e.bands['5_10km'].tiv),'Distance-band total','orange')+metric('CURRENT THREAT ENVELOPE',fmt(e.scenario.policies),'Policies intersecting','red')+metric('INDICATIVE INSURED LOSS',`${euro(e.estimates.loss_low)}–${euro(e.estimates.loss_high)}`,'Planning range','red');drawEvent($('#portfolio-map'),e.scenario_geometry,true);const rows=[['Event area','inside'],['< 1 km','0_1km'],['1–3 km','1_3km'],['3–5 km','3_5km'],['5–10 km','5_10km']];$('#exposure-table').innerHTML=rows.map(([label,key])=>`<div class="exposure-row"><span>${label}</span><b>${fmt(e.bands[key].policies)}</b><strong>${euro(e.bands[key].tiv)}</strong></div>`).join('')+`<div class="exposure-total"><span>SCENARIO TOTAL</span><b>${fmt(e.scenario.policies)}</b><strong>${euro(e.scenario.tiv)}</strong></div>`}
function renderScenario(){const e=state.exposure,s=SCENARIOS[state.scenario];$('#scenario-name').textContent=title(state.scenario);$('#scenario-geometry-label').textContent=`${title(state.scenario)} · ${s.spread_km} km spread · wind ${String(state.event.wind_direction).padStart(3,'0')}°`;$('#wind-readout').textContent=`${String(state.event.wind_direction).padStart(3,'0')}° / ${state.event.wind_speed_kmh} km/h`;$('#scenario-stats').innerHTML=metric('POLICIES EXPOSED',fmt(e.scenario.policies),'Intersecting envelope')+metric('TOTAL TIV',euro(e.scenario.tiv),'Building + contents','orange')+metric('LOSS RANGE',`${euro(e.estimates.loss_low)}–${euro(e.estimates.loss_high)}`,'Indicative insured loss','red')+metric('EXPECTED CLAIMS',`${fmt(e.estimates.claims_low)}–${fmt(e.estimates.claims_high)}`,'Planning estimate');drawEvent($('#scenario-map'),e.scenario_geometry);const r=e.reinsurance;$('#retention').textContent=euro(r.retention);$('#reins-status').innerHTML=`<b>${r.status}</b><span>${r.ceded_loss_high?`Potential ceded loss ${euro(r.ceded_loss_low)}–${euro(r.ceded_loss_high)}`:'No expected treaty recovery'}</span>`;$('#reins-fill').style.width=`${Math.min(100,e.estimates.loss_high/r.retention*100)}%`;$$('#scenario-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.scenario===state.scenario));}
function renderActions(){const severe=state.cache?.severe||state.exposure;$('#action-loss').textContent=`${euro(severe.estimates.loss_low)}–${euro(severe.estimates.loss_high)}`;$('#actions-grid').innerHTML=state.actions.map(a=>`<article class="action-card ${a.status==='Completed'?'done':''}"><div class="action-card-head"><span class="action-team">${a.team}</span><select data-action="${a.id}"><option ${a.status==='Not started'?'selected':''}>Not started</option><option ${a.status==='In progress'?'selected':''}>In progress</option><option ${a.status==='Completed'?'selected':''}>Completed</option></select></div><h3>${a.title}</h3><p>${a.detail}</p><div class="action-foot"><span class="action-check">${a.status==='Completed'?'✓':'○'}</span><span>${a.status}</span></div></article>`).join('');const done=state.actions.filter(a=>a.status==='Completed').length;$('#action-summary').textContent=`${done} / ${state.actions.length} complete`;$$('select[data-action]').forEach(s=>s.onchange=async()=>{const data=await fetch(`/api/actions/${s.dataset.action}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})}).then(r=>r.json());state.actions=data.actions;renderActions();toast('Action status updated')})}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));window.scrollTo(0,0)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function load(){try{const [events,health,timeline,actions]=await Promise.all([api('/api/events'),api('/api/health'),api('/api/events/evt-huertgenwald-2022/timeline'),api('/api/events/evt-huertgenwald-2022/actions')]);state.event=events.events[0];state.sources=health.sources;state.mode=health.mode;state.timeline=timeline.snapshots;state.actions=actions.actions;state.firms=(await api('/api/events/evt-huertgenwald-2022/signals')).firms.observations;state.warning=(await api('/api/events/evt-huertgenwald-2022/signals')).warning.geometry? (await api('/api/events/evt-huertgenwald-2022/signals')).warning:null;state.event.wind_direction=state.event.wind_direction||70;state.event.wind_speed_kmh=state.event.wind_speed_kmh||31;await refresh();renderSources();renderActions();}catch(err){toast('Could not load radar data');console.error(err)}}
async function refresh(){const [risk,exposure]=await Promise.all([api(`/api/events/${state.event.id}/risk?at=${state.at}`),api(`/api/events/${state.event.id}/exposure?scenario=${state.scenario}&at=${state.at}`)]);state.risk=risk;state.exposure=exposure;state.cache=state.cache||{};for(const key of ['current','adverse','severe'])state.cache[key]=await api(`/api/events/${state.event.id}/exposure?scenario=${key}&at=${state.at}`);renderRadar();renderRisk();renderPortfolio();renderScenario();renderActions();$('#updated-label').textContent=state.timeline[state.at]?.label||'Now';}
$$('.nav-item').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$$('.scenario-tabs button').forEach(b=>b.onclick=async()=>{state.scenario=b.dataset.scenario;await refresh()});$$('.toggle-btn').forEach(b=>b.onclick=()=>{if(b.dataset.mode==='live')toast('Live connectors are configured server-side; replay remains the safe demo path');else toast('Historical replay selected')});['#why-risk','#why-risk-2'].forEach(s=>$(s).onclick=()=>$('#why-box').classList.toggle('hidden'));$('#why-exposure').onclick=()=>toast('Counts use point-in-envelope and haversine distance bands; TIV is summed from synthetic policies.');$('#reset-demo').onclick=()=>{state.at=3;state.scenario='current';load();toast('Demo reset to final replay snapshot')};load();
const timelineTimer=setInterval(()=>{if(state.timeline.length){renderTimeline();clearInterval(timelineTimer)}},100);
setupLeafletMaps();
setInterval(()=>{if(state.exposure)updateLeafletLayers()},1000);
setInterval(()=>{if(state.risk){const p=$('#why-box p');if(p)p.textContent=state.risk.method}},500);
